---
kind: pipeline
name: amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: sonobuoy-e2e-tests
  image: rancher/dapper:v0.4.1
  commands:
  - dapper -f Dockerfile.sonobuoy.dapper sonobuoy-e2e-tests
  volumes:
  - name: docker
    path: /var/run/docker.sock
  when:
    instance:
    - drone-publish.rancher.io
    ref:
      include:
      - refs/head/master
      - refs/tags/*
      exclude:
      - refs/tags/*-k2s.*
    event:
    - tag

- name: github_binary_release
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-amd64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "rancher/k2s"
    tag: "${DRONE_TAG}-amd64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: rancher/dapper:v0.4.1
  commands:
  - dapper ci
  volumes:
  - name: docker
    path: /var/run/docker.sock

- name: github_binary_release
  image: ibuildthecloud/github-release:v0.0.1
  settings:
    api_key:
      from_secret: github_token
    prerelease: true
    checksum:
    - sha256
    checksum_file: CHECKSUMsum-arm64.txt
    checksum_flatten: true
    files:
    - "dist/artifacts/*"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

- name: docker-publish
  image: plugins/docker
  settings:
    dockerfile: package/Dockerfile
    password:
      from_secret: docker_password
    repo: "Yuwenfeng2019/K2S"
    tag: "${DRONE_TAG}-arm64"
    username:
      from_secret: docker_username
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

volumes:
- name: docker
  host:
    path: /var/run/docker.sock


---
kind: pipeline
name: manifest

platform:
  os: linux
  arch: arm64

steps:
- name: manifest
  image: plugins/manifest:1.0.2
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    platforms:
      - linux/arm64
    target: "Yuwenfeng2019/K2S:${DRONE_TAG}"
    template: "Yuwenfeng2019/K2S:${DRONE_TAG}-ARCH"
  when:
    instance:
    - drone-publish.rancher.io
    ref:
    - refs/head/master
    - refs/tags/*
    event:
    - tag

depends_on:
- arm64
