# to run define K2S_TOKEN, K2S_VERSION is optional, eg:
#   K2S_TOKEN=${RANDOM}${RANDOM}${RANDOM} docker-compose up

version: '3'
services:

  server:
    image: "Yuwenfeng2019/k2s:${K2S_VERSION:-latest}"
    command: server
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K2S_TOKEN=${K2S_TOKEN:?err}
    - K2S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K2S_KUBECONFIG_MODE=666
    volumes:
    - k2s-server:/var/lib/yuwenfeng/k2s
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  agent:
    image: "Yuwenfeng2019/k2s:${K2S_VERSION:-latest}"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K2S_URL=https://server:6443
    - K2S_TOKEN=${K2S_TOKEN:?err}

volumes:
  k2s-server: {}
