version: '3'
services:
  node:
    image: Yuwenfeng2019/K2S:v0.5.0
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K2S_URL=https://server:6443
    - K2S_CLUSTER_SECRET=somethingtotallyrandom
    # Can also use K2S_TOKEN from /var/lib/k2s/server/node-token instead of K2S_CLUSTER_SECRET
    #- K2S_TOKEN=K13849a67fc385fd3c0fa6133a8649d9e717b0258b3b09c87ffc33dae362c12d8c0::node:2e373dca319a0525745fd8b3d8120d9c
